#!/bin/bash
source ./colors.sh "$@"
source ./system_info.sh

echo -e "\e[${NAME_BG}m\e[${NAME_FG}mHOSTNAME\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$HOSTNAME\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mTIMEZONE\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$TIMEZONE\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mUSER\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$USER\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mOS\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$OS\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mDATE\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$DATE\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mUPTIME\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$UPTIME\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mUPTIME_SEC\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$UPTIME_SEC\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mIP\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$IP\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mMASK\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$MASK\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mGATEWAY\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$GATEWAY\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mRAM_TOTAL\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$RAM_TOTAL\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mRAM_USED\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$RAM_USED\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mRAM_FREE\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$RAM_FREE\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mSPACE_ROOT\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$SPACE_ROOT\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mSPACE_ROOT_USED\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$SPACE_ROOT_USED\e[0m"
echo -e "\e[${NAME_BG}m\e[${NAME_FG}mSPACE_ROOT_FREE\e[0m = \e[${VALUE_BG}m\e[${VALUE_FG}m$SPACE_ROOT_FREE\e[0m"
