#!/bin/bash
HOSTNAME=$(hostname)
TIMEZONE="$(timedatectl | grep "Time zone" | awk '{print $3, "UTC", $5}')"
USER=$(whoami)
OS=$(lsb_release -d | awk -F"\t" '{print $2}')
DATE=$(date "+%d %b %Y %H:%M:%S")
UPTIME=$(uptime -p)
UPTIME_SEC=$(cat /proc/uptime | awk '{print int($1)}')
IP=$(hostname -I | awk '{print $1}')
MASK=$(ifconfig | grep -w "netmask" | awk '{print $4}' | head -n1)
GATEWAY=$(ip route | grep default | awk '{print $3}')
RAM_TOTAL=$(free -g | awk '/Mem:/ {printf "%.3f", $2}')
RAM_USED=$(free -g | awk '/Mem:/ {printf "%.3f", $3}')
RAM_FREE=$(free -g | awk '/Mem:/ {printf "%.3f", $4}')
SPACE_ROOT=$(df -m / | awk 'NR==2{printf "%.2f", $2}')
SPACE_ROOT_USED=$(df -m / | awk 'NR==2{printf "%.2f", $3}')
SPACE_ROOT_FREE=$(df -m / | awk 'NR==2{printf "%.2f", $4}')
